# PeakFlow pipeline. From a clean clone:
#   conda env create -f environment.lock.yml && conda activate reuse-ready && make all
# environment.lock.yml pins every package (exported from the development env, no build strings);
# environment.yml lists only the direct dependencies at the same versions (`make env-lock` rewrites the lock).
# Every recipe line is a separate shell command; make stops at the first non-zero exit.
# `make all` is offline after `make data`: the live URL check of site sources runs only in `make urls`.

SHELL  := /bin/bash
PYTHON ?= python
PY     := PYTHONPATH=src $(PYTHON)
# Fixed timestamp for reproducible PDF/SVG metadata.
export SOURCE_DATE_EPOCH ?= 1790000000
CONDA  ?= conda
ENV    ?= reuse-ready

.PHONY: all data model table map urls figures_v2 figures_v3 falls_figures site_blindspot uncertainty tradeoff cycles wqp docs test clean verify-manifest env-lock

all: data model table map figures_v2 figures_v3 falls_figures site_blindspot uncertainty tradeoff cycles docs test

# Raw downloads (idempotent; cached files reused, MANIFEST rows ensured) + DRB boundary + ECHO + weather.
# fetch covers every raw file the pipeline reads, including the DRBC rule PDF and data-centers page, the four
# Falls Township press pages, the LBNL 2024 report and the Natural Earth populated places archive.
# The final --verify exits non-zero if any MANIFEST row's file is missing or its SHA-256 differs.

# Build order (targets read outputs of these prerequisites).
model: data
table: model
map: model
figures_v2: map
figures_v3: figures_v2
falls_figures: table
site_blindspot: map table
uncertainty: figures_v2 table
tradeoff: map table
cycles: map
docs: falls_figures figures_v3 uncertainty tradeoff cycles site_blindspot
test: docs

data:
	$(PY) -m reuse_ready.fetch
	$(PY) -c "from reuse_ready import echo; echo.run(download=True)"
	$(PY) -c "from reuse_ready import weather; weather.run(download_first=False)"
	$(PY) -m reuse_ready.fetch --verify

# Wet-bulb cooling-water model calibration -> results/calibration.json; implied WUE -> results/falls_implied_wue.json
model:
	$(PY) -m reuse_ready.calibration
	$(PY) -m reuse_ready.wue

# Trenton flow statistics + blind-spot table -> results/flow_*, results/table_blindspot.*, figures/table_blindspot.*
table:
	$(PY) -c "from reuse_ready import flow; flow.run(fetch=False)"
	$(PY) -m reuse_ready.blindspot

# Site classification (cached URL check, no network), supply screen, interactive HTML map.
# sites.run also writes the 'sites' rows of results/exclusions.csv (inactive, non-data-center, near-miss).
map:
	$(PY) -c "from reuse_ready import sites; sites.run(check=False)"
	$(PY) -m reuse_ready.supply_screen
	$(PY) -m reuse_ready.plotting.supply_map

# Live HTTP check of every site source and replacement URL -> data/processed/site_url_check.csv (network;
# results vary by day). Not part of `all`; run `make urls map` to refresh the check and rebuild the map.
urls:
	$(PY) -m reuse_ready.urlcheck

# Bar chart, Falls/Plymouth detail and site key (figures_v2); needs results from `make map`.
figures_v2:
	$(PY) -m reuse_ready.plotting.figures_v2

# Supply-screen map, full (supply_screen_map, 180 mm) and brief (supply_screen_map_brief, 120 mm).
figures_v3:
	$(PY) -m reuse_ready.plotting.figures_v3

# sources.md (generated by reuse_ready.docs from references.bib); fails on undefined keys or non-verbatim passages
# Part 2 (items 9-11): Falls duration curve, drought coincidence, per-site blind spot with supplier classes.
falls_figures:
	$(PY) -m reuse_ready.falls_figures

site_blindspot:
	$(PY) -m reuse_ready.suppliers
	$(PY) -m reuse_ready.site_blindspot --no-wait

# Part 4 (item 14): Monte Carlo peak-day uncertainty; peak_uncertainty, sites_mc_ridgeline and falls_mc_fan figures.
uncertainty:
	$(PY) -m reuse_ready.uncertainty
	$(PY) -m reuse_ready.plotting.peak_uncertainty

# Part 5 (item 15): water-energy frontier from LBNL 2024 Figure 4.4 and the calibrated model.
tradeoff:
	$(PY) -m reuse_ready.tradeoff

# Water Quality Portal retrieval for the cycles screen (network; not part of `all`, like `urls`).
wqp:
	$(PY) -m reuse_ready.wqp

# Part 3 (items 12-13): cycles of concentration. reuse_ready.wqp is networked on first run and offline afterwards
# (cache in data/raw/wqp/); when the Water Quality Portal is unreachable it records the failure and cycles uses
# literature makeup quality, marking every row assumed.
cycles:
	$(PY) -m reuse_ready.wqp --offline
	$(PY) -m reuse_ready.cycles
	$(PY) -m reuse_ready.plotting.cycles_constraints

docs:
	$(PY) -m reuse_ready.docs

test:
	$(PY) -m pytest -q

# Existence and SHA-256 of every MANIFEST row; non-zero exit lists each failure.
verify-manifest:
	$(PY) -m reuse_ready.fetch --verify

# Rewrite environment.lock.yml from the active conda env (header comments must be re-added by hand).
env-lock:
	$(CONDA) env export -n $(ENV) --no-builds | grep -v '^prefix:' > environment.lock.yml

# Remove generated outputs. Never touches data/raw, data/sites, audit/.
# Kept on purpose: data/processed/site_url_verification.csv (hand-curated content check, no generating code in
# src/) and data/processed/site_url_check.csv (cached live check; regenerate only with `make urls`).
KEEP_PROCESSED := site_url_verification.csv site_url_check.csv
KEEP_RESULTS   := results.md pending_approvals.md brief_numbers.md
clean:
	find data/processed -mindepth 1 -type f $(foreach k,$(KEEP_PROCESSED),! -name '$(k)') -delete
	find results -mindepth 1 -type f $(foreach k,$(KEEP_RESULTS),! -name '$(k)') -delete
	find figures -mindepth 1 -type f -delete
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
	rm -rf .pytest_cache
