# PeakFlow pipeline. From a clean clone:
#   conda env create -f environment.lock.yml && conda activate peakflow && make all
# environment.lock.yml pins every package (exported from the development env, no build strings);
# environment.yml lists only the direct dependencies at the same versions (`make env-lock` rewrites the lock).
# Every recipe line is a separate shell command; make stops at the first non-zero exit.
# `make all` is offline after `make data`: the live URL check of site sources runs only in `make urls`.

SHELL  := /bin/bash
PYTHON ?= python
PY     := PYTHONPATH=src $(PYTHON)
# Fixed timestamp for reproducible PDF/SVG metadata.
export SOURCE_DATE_EPOCH ?= 1790000000
CONDA  ?= conda
ENV    ?= peakflow
# pyproj needs the PROJ database (proj.db). Unless PROJ_DATA is already set, point it at share/proj of the
# conda environment that $(PYTHON) belongs to (CONDA_PREFIX when activated, else resolved from the interpreter).
ifeq ($(origin PROJ_DATA),undefined)
PROJ_DATA := $(shell $(PYTHON) -c "import os,sys; d=[os.path.join(p,'share','proj') for p in (os.environ.get('CONDA_PREFIX',''), os.path.dirname(os.path.dirname(os.path.realpath(sys.executable))))]; print(next((x for x in d if os.path.isfile(os.path.join(x,'proj.db'))),''))")
endif
ifneq ($(PROJ_DATA),)
export PROJ_DATA
endif

.PHONY: all data model table map urls supply_figures falls_figures site_blindspot uncertainty tradeoff cycles wqp docs test clean verify-manifest env-lock

all: data model table map supply_figures falls_figures site_blindspot uncertainty tradeoff cycles docs test

# Build order (targets read outputs of these prerequisites).
model: data
table: model
map: model
supply_figures: map
falls_figures: table
site_blindspot: map table
uncertainty: supply_figures table
tradeoff: map table
cycles: map
docs: falls_figures supply_figures uncertainty tradeoff cycles site_blindspot
test: docs

# Raw downloads (idempotent; cached files reused, MANIFEST rows ensured) + DRB boundary + ECHO + weather.
# fetch covers every raw file the pipeline reads, including the DRBC rule PDF and data-centers page, the four
# Falls Township press pages, the LBNL 2024 report and the Natural Earth populated places archive.
# The final --verify exits non-zero if any MANIFEST row's file is missing or its SHA-256 differs.
data:
	$(PY) -m peakflow.fetch
	$(PY) -c "from peakflow import echo; echo.run(download=True)"
	$(PY) -c "from peakflow import weather; weather.run(download_first=False)"
	$(PY) -m peakflow.fetch --verify

# Wet-bulb cooling-water model calibration -> results/calibration.json; implied WUE -> results/falls_implied_wue.json
model:
	$(PY) -m peakflow.calibration
	$(PY) -m peakflow.wue

# Trenton flow statistics + blind-spot table -> results/flow_*, results/table_blindspot.*, figures/table_blindspot.*
table:
	$(PY) -c "from peakflow import flow; flow.run(fetch=False)"
	$(PY) -m peakflow.blindspot

# Site classification (cached URL check, no network), supply screen, interactive HTML map.
# sites.run also writes the 'sites' rows of results/exclusions.csv (inactive, non-data-center, near-miss).
map:
	$(PY) -c "from peakflow import sites; sites.run(check=False)"
	$(PY) -m peakflow.supply_screen
	$(PY) -m peakflow.plotting.supply_map

# Live HTTP check of every site source and replacement URL -> data/processed/site_url_check.csv (network;
# results vary by day). Not part of `all`; run `make urls map` to refresh the check and rebuild the map.
urls:
	$(PY) -m peakflow.urlcheck

# Supply-screen map (180 mm and 120 mm brief), bar chart, Falls/Plymouth detail and site key; needs results from
# `make map`.
supply_figures:
	$(PY) -m peakflow.plotting.supply_figures

# Falls duration curve, drought coincidence and per-site blind spot with supplier classes.
falls_figures:
	$(PY) -m peakflow.falls_figures

site_blindspot:
	$(PY) -m peakflow.suppliers
	$(PY) -m peakflow.site_blindspot --no-wait

# Monte Carlo peak-day uncertainty: peak_uncertainty, sites_mc_ridgeline and falls_mc_fan figures.
uncertainty:
	$(PY) -m peakflow.uncertainty
	$(PY) -m peakflow.plotting.peak_uncertainty

# Water-energy frontier from LBNL 2024 Figure 4.4 and the calibrated model.
tradeoff:
	$(PY) -m peakflow.tradeoff

# Water Quality Portal retrieval for the cycles screen (network; not part of `all`, like `urls`).
wqp:
	$(PY) -m peakflow.wqp

# Cycles of concentration. peakflow.wqp is networked on first run and offline afterwards
# (cache in data/raw/wqp/); when the Water Quality Portal is unreachable it records the failure and cycles uses
# literature makeup quality, marking every row assumed.
cycles:
	$(PY) -m peakflow.wqp --offline
	$(PY) -m peakflow.cycles
	$(PY) -m peakflow.plotting.cycles_constraints

# sources.md (generated by peakflow.docs from references.bib); fails on undefined keys or non-verbatim passages
docs:
	$(PY) -m peakflow.docs

test:
	$(PY) -m pytest -q

# Existence and SHA-256 of every MANIFEST row; non-zero exit lists each failure.
verify-manifest:
	$(PY) -m peakflow.fetch --verify

# Rewrite environment.lock.yml from the active conda env (header comments must be re-added by hand).
env-lock:
	$(CONDA) env export -n $(ENV) --no-builds | grep -v '^prefix:' > environment.lock.yml

# Remove generated outputs. Never touches data/raw or data/sites.
# Retained: data/processed/site_url_verification.csv (hand-curated content check, no generating code in
# src/) and data/processed/site_url_check.csv (cached live check; regenerate only with `make urls`).
KEEP_PROCESSED := site_url_verification.csv site_url_check.csv
KEEP_RESULTS   := results.md brief_numbers.md
clean:
	find data/processed -mindepth 1 -type f $(foreach k,$(KEEP_PROCESSED),! -name '$(k)') -delete
	find results -mindepth 1 -type f $(foreach k,$(KEEP_RESULTS),! -name '$(k)') -delete
	find figures -mindepth 1 -type f -delete
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
	rm -rf .pytest_cache
