"""Repository paths, provenance manifest, and exclusion logging."""
from __future__ import annotations

import csv
import datetime as dt
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"
SITES = ROOT / "data" / "sites"
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"
MANIFEST = RAW / "MANIFEST.md"
EXCLUSIONS = RESULTS / "exclusions.csv"

for _p in (RAW, PROCESSED, SITES, RESULTS, FIGURES):
    _p.mkdir(parents=True, exist_ok=True)

USER_AGENT = "reuse-ready-research/0.1 (reproducible research repository)"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def count_rows(path: Path) -> int:
    """Row count: data lines for delimited text, features for GeoJSON, lines otherwise."""
    p = Path(path)
    if p.suffix == ".geojson":
        import json

        return len(json.loads(p.read_text())["features"])
    with open(p, "rb") as fh:
        n = sum(1 for _ in fh)
    if p.suffix in (".csv",):
        return max(n - 1, 0)
    if p.suffix == ".rdb":
        with open(p, errors="ignore") as fh:
            return sum(1 for ln in fh if ln.startswith("USGS\t"))
    return n


MANIFEST_COLS = ["file", "source_url", "downloaded_utc", "rows", "sha256", "note"]


def read_manifest() -> dict[str, list[str]]:
    """Rows of data/raw/MANIFEST.md keyed by file (relative to data/raw); older 5-column rows padded."""
    rows = {}
    if MANIFEST.exists():
        for ln in MANIFEST.read_text().splitlines():
            if ln.startswith("| ") and not ln.startswith("| file ") and not ln.startswith("| ---"):
                cells = [c.strip() for c in ln.strip().strip("|").split("|")]
                cells += [""] * (len(MANIFEST_COLS) - len(cells))
                rows[cells[0]] = cells[: len(MANIFEST_COLS)]
    return rows


def record_download(path: Path, url: str, when: dt.datetime | None = None, note: str = "") -> None:
    """Append or replace a row in data/raw/MANIFEST.md for one raw file.

    ``when`` defaults to now (UTC); pass e.g. the file mtime when recording a file that was
    already on disk. ``note`` is an optional free-text column (empty by default).
    """
    path = Path(path)
    when = when or dt.datetime.now(dt.timezone.utc)
    rel = path.relative_to(RAW).as_posix()
    rows = read_manifest()
    rows[rel] = [rel, url, when.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                 str(count_rows(path)), sha256(path), note]
    lines = [
        "# Raw data manifest",
        "",
        "Generated by `make data`. One row per raw file: source URL, UTC download timestamp, row count, SHA-256, "
        "and an optional note (e.g. 'recorded from existing file' when downloaded_utc is the file mtime).",
        "",
        "| " + " | ".join(MANIFEST_COLS) + " |",
        "| " + " | ".join("---" for _ in MANIFEST_COLS) + " |",
    ]
    lines += ["| " + " | ".join(r) + " |" for _, r in sorted(rows.items())]
    MANIFEST.write_text("\n".join(lines) + "\n")


EXCLUSION_STAGE_ORDER = ("sites", "weather", "echo_permittees", "echo_no_dmr_flow", "supply_screen")


def log_exclusions(stage: str, records: list[dict]) -> None:
    """Replace all exclusion rows for one pipeline stage in results/exclusions.csv."""
    cols = ["stage", "record_id", "record_name", "reason"]
    existing = []
    if EXCLUSIONS.exists():
        with open(EXCLUSIONS) as fh:
            existing = [r for r in csv.DictReader(fh) if r["stage"] != stage]
    new = [{"stage": stage, **{k: r.get(k, "") for k in cols[1:]}} for r in records]
    with open(EXCLUSIONS, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        order = {k: i for i, k in enumerate(EXCLUSION_STAGE_ORDER)}
        rows = sorted(existing + new, key=lambda r: (order.get(r["stage"], len(order)), r["stage"],
                                                    str(r["record_id"])))
        w.writerows(rows)
